/**
 * Generates supabase/seed.sql from the shared seed catalogue so the demo backend and the
 * Supabase database always start from identical vendors, storefronts and products.
 * Run: npm run seed:sql
 */
import { writeFileSync } from "node:fs"
import { seedProducts, seedStorefronts, seedVendors } from "../src/data/seed-catalog.ts"
import { DEFAULT_SETTINGS } from "../supabase/functions/_shared/domain/catalog.ts"

const now = new Date()
const vendors = seedVendors(now)
const products = seedProducts(now)
const storefronts = seedStorefronts(now, vendors, products)

const q = (v: unknown): string => {
  if (v === null || v === undefined) return "null"
  if (typeof v === "object" && v !== null && "__json" in v) return `'${JSON.stringify((v as { __json: unknown }).__json).replace(/'/g, "''")}'::jsonb`
  if (typeof v === "number") return String(v)
  if (typeof v === "boolean") return v ? "true" : "false"
  if (Array.isArray(v) && v.every((x) => typeof x === "string")) return `array[${v.map(q).join(",")}]::text[]`
  if (typeof v === "object") return `'${JSON.stringify(v).replace(/'/g, "''")}'::jsonb`
  return `'${String(v).replace(/'/g, "''")}'`
}
/** Forces jsonb encoding (empty arrays are otherwise ambiguous with text[]). */
const J = (v: unknown) => ({ __json: v })
const row = (vals: unknown[]) => `(${vals.map(q).join(", ")})`

let sql = `-- Generated by scripts/generate-seed-sql.ts on ${now.toISOString()}. Do not edit by hand.\n-- Development and staging only: fictional vendors and products.\n\n`
sql += `insert into public.platform_settings (id, settings) values (true, ${q(DEFAULT_SETTINGS)}) on conflict (id) do update set settings = excluded.settings;\n\n`

sql += `insert into public.vendors (id, slug, name, tagline, about, logo_initials, logo_color, cover_image, status, verified, zones, operating, fulfilment, categories, business_type, city, response_hours, featured, joined_at, return_policy, delivery_policy) values\n`
sql += vendors.map((v) => row([v.id, v.slug, v.name, v.tagline, v.about, v.logoInitials, v.logoColor, v.coverImage, v.status, v.verified, J(v.zones), J(v.operating), v.fulfilment, v.categories, v.businessType, v.city, v.responseHours, v.featured, v.joinedAt, v.returnPolicy, v.deliveryPolicy])).join(",\n") + "\non conflict (id) do nothing;\n\n"

sql += `insert into public.storefronts (id, vendor_id, slug, status, headline, intro, accent, layout, cover_image, featured_product_ids, collections, published_at, slug_history) values\n`
sql += storefronts.map((s) => row([s.id, s.vendorId, s.slug, s.status, s.headline, s.intro, s.accent, s.layout, s.coverImage, s.featuredProductIds, J(s.collections), s.publishedAt, s.slugHistory])).join(",\n") + "\non conflict (id) do nothing;\n\n"

sql += `insert into public.products (id, vendor_id, slug, title, summary, description, included, dimensions, images, category, occasions, interests, status, prep_hours, perishable, highly_customised, return_eligible, personalisation, wrapping, sponsored, editorial_score, moderation_note, created_at) values\n`
sql += products.map((p) => row([p.id, p.vendorId, p.slug, p.title, p.summary, p.description, p.included, p.dimensions ?? null, p.images, p.category, p.occasions, p.interests, p.status, p.prepHours, p.perishable, p.highlyCustomised, p.returnEligible, p.personalisation ? J(p.personalisation) : null, J(p.wrapping), p.sponsored, p.editorialScore, p.moderationNote ?? null, p.createdAt])).join(",\n") + "\non conflict (id) do nothing;\n\n"

sql += `insert into public.variants (id, product_id, name, sku, price, stock, position) values\n`
sql += products.flatMap((p) => p.variants.map((v, i) => row([v.id, p.id, v.name, v.sku, v.price, v.stock, i]))).join(",\n") + "\non conflict (id) do nothing;\n"

writeFileSync(new URL("../supabase/seed.sql", import.meta.url), sql)
console.log(`seed.sql: ${vendors.length} vendors, ${storefronts.length} storefronts, ${products.length} products`)
